const actionTypes = {
    GET_ALL_APPLICATION : 'GET_ALL_APPLICATION',
    SET_ALL_APPLICATION : "SET_ALL_APPLICATION",

    GET_SELECTED_APP :"GET_SELECTED_APP",
    SET_SELECTED_APP :"SET_SELECTED_APP",

    GET_ALL_TEMPLATE : "GET_ALL_TEMPLATE",
    SET_ALL_TEMPLATE : "SET_ALL_TEMPLATE",

    GET_ALL_NOTIFICATION : "GET_ALL_NOTIFICATION",
    SET_ALL_NOTIFICATION : "SET_ALL_NOTIFICATION",

    SET_ALL_TMP_DATA :"SET_ALL_TMP_DATA",
    SET_ALL_NOT_DATA : "SET_ALL_NOT_DATA",

    GET_ALL_REPORTS : "GET_ALL_REPORTS",
    SET_ALL_REPORTS : "SET_ALL_REPORTS",

    STATUS_UPDATE : "STATUS_UPDATE",
    STATUS_UPDATE_SUCCESS : "STATUS_UPDATE_SUCCESS",

    GET_SAMPLE_PAYLOAD : "GET_SAMPLE_PAYLOAD",
    SET_SAMPLE_PAYLOAD : "SET_SAMPLE_PAYLOAD",

    GET_ALL_NOT_TMP_DATA : "GET_ALL_NOT_TMP_DATA",
    SET_ALL_NOT_TMP_DATA : "SET_ALL_NOT_TMP_DATA",

    SET_CASH_MAP : "SET_CASH_MAP",
  ADD_NOTIFICATION : "ADD_NOTIFICATION",
  EDIT_NOTIFICATION : "EDIT_NOTIFICATION",

  GET_ALL_CHANNEL:"GET_ALL_CHANNEL",
  SET_ALL_CHANNEL:"SET_ALL_CHANNEL",

  GET_NOTIFICATION_LIST: "GET_NOTIFICATION_LIST",
  SET_NOTIFICATION_LIST: "SET_NOTIFICATION_LIST",
}

export default actionTypes