const actionTypes = {
    GET_ALL_APPLICATION : 'GET_ALL_APPLICATION',
    SET_ALL_APPLICATION : "SET_ALL_APPLICATION",
    GET_SELECTED_APP :"GET_SELECTED_APP",
    SET_SELECTED_APP :"SET_SELECTED_APP"
}

export default actionTypes